### ISSUE TITLE
Build instructions no longer working on linux

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/CUDA_SIMrecon#8]
Hi @linshaova,

I'm trying to get this building locally again to help out with #6 and #7 but the build instructions for linux in the readme are no longer working for me.  If I roll back to the last commit I used 279c210724488290ac35622ad327a6916ed86505 it does build... but on the current master I had to first install a few things, play around with the findFFTW routine for a while, and now it's unable to find X11 when building gpuFunctions.
```make
(simbuild) talley@home-ubuntu:~/python/cudasirecon/build(master)$ make
Scanning dependencies of target Buffer
[  6%] Building CXX object Buffers/CMakeFiles/Buffer.dir/Buffer.cpp.o
[ 13%] Building CXX object Buffers/CMakeFiles/Buffer.dir/bufferExample.cpp.o
[ 20%] Building CXX object Buffers/CMakeFiles/Buffer.dir/CPUBuffer.cpp.o
[ 26%] Building CXX object Buffers/CMakeFiles/Buffer.dir/GPUBuffer.cpp.o
[ 33%] Building CXX object Buffers/CMakeFiles/Buffer.dir/PinnedCPUBuffer.cpp.o
[ 40%] Linking CXX static library libBuffer.a
[ 40%] Built target Buffer
[ 46%] Building NVCC (Device) object cudaSirecon/CMakeFiles/gpuFunctions.dir/gpuFunctions_generated_gpuFunctionsImpl.cu.o
In file included from /home/talley/python/cudasirecon/cudaSirecon/cudaSireconImpl.h:36:0,
                 from /home/talley/python/cudasirecon/cudaSirecon/gpuFunctions.h:5,
                 from /home/talley/python/cudasirecon/cudaSirecon/gpuFunctionsImpl_hh.cu:4,
                 from /home/talley/python/cudasirecon/cudaSirecon/gpuFunctionsImpl.cu:1:
/home/talley/python/cudasirecon/cudaSirecon/CImg.h:236:22: fatal error: X11/Xlib.h: No such file or directory
compilation terminated.
CMake Error at gpuFunctions_generated_gpuFunctionsImpl.cu.o.Release.cmake:220 (message):
  Error generating
  /home/talley/python/cudasirecon/build/cudaSirecon/CMakeFiles/gpuFunctions.dir//./gpuFunctions_generated_gpuFunctionsImpl.cu.o


cudaSirecon/CMakeFiles/gpuFunctions.dir/build.make:80: recipe for target 'cudaSirecon/CMakeFiles/gpuFunctions.dir/gpuFunctions_generated_gpuFunctionsImpl.cu.o' failed
make[2]: *** [cudaSirecon/CMakeFiles/gpuFunctions.dir/gpuFunctions_generated_gpuFunctionsImpl.cu.o] Error 1
CMakeFiles/Makefile2:211: recipe for target 'cudaSirecon/CMakeFiles/gpuFunctions.dir/all' failed
make[1]: *** [cudaSirecon/CMakeFiles/gpuFunctions.dir/all] Error 2
Makefile:157: recipe for target 'all' failed
make: *** [all] Error 2
```

When you have a moment, would you mind trying to strictly follow the build instructions for linux in the readme (using a fresh conda env) and update it with any additional things you needed to install (like conda install fftw?) to get it to build for you in your local `simbuild` environment?

**Comment by tlambert03** [comment]
I will add one thing... for blas, x11, and lapack, I added this somewhere in cudaSirecon/CmakeLists.txt:
```cmake
  find_library(BLAS blas REQUIRED)
  find_library(LAPACK lapack REQUIRED)
  find_library(X11 X11 REQUIRED)
```
and then used `${BLAS}`, `${LAPACK}` and `${X11}` in the link_libraries directive here:
https://github.com/scopetools/cudasirecon/blob/99bc478fde5c5c9b5c6d125946f4af124a9efd80/cudaSirecon/CMakeLists.txt#L124-L137

that seemed to do a better job that the current literals

**Comment by GenevieveBuckley** [comment]
Hi @tlambert03, since @linshaova is a bit busy I thought I'd have a go at building cudasirecon on our local Ubuntu linux machine.

Where do I get the PRISM/IVE libraries from?
> The program requires the IVE/Priism libraries, which are not distributed with this source code and must be acquired seperately from UCSF. Place them in a folder called IVE at the top level of the source folder (same folder as the cudaSirecon folder). 

This [seemed like the best match](https://medicine.ucsf.edu/innovations/informatics/prism), but I don't understand where I can actually download the libraries from. (I also [found this](https://github.com/PrismLibrary) but it doesn't seem like the right one.)

**Comment by GenevieveBuckley** [comment]
Mind you, this might not be necessary for me? I have a working `cudasirecon` and a working `makeotf` on linux now - the main problem will be figuring out what our config settings should look like & getting our data into the right shape/format for input.

**Comment by dmilkie** [comment]
The original PRIISM/IVE  (note it's "PRIISM" not "PRISM") site is gone. Wayback Machine has some records of it.  Randomly picking a date gives me some downloads you can give a shot with:
http://web.archive.org/web/20161029043546/http://www.msg.ucsf.edu/IVE/

**Comment by tlambert03** [comment]
I sent her the libraries... (no one at UCSF seems to be managing them anymore).  if someone else needs them, let me know

**Comment by GenevieveBuckley** [comment]
I've been following the linux build instructions from the README, and this is how it went.

- [x] Added the `IVE` library as a sub-directory of the cudasirecon repository (thanks for sharing that with me, Talley)
- [x] Created a `simbuild` conda environment with the specified dependencies
- [x] Exported the environment variables
- [ ] I[m having problems when it gets to running the `cmake` command.

When I first ran the `cmake` command it complained about not being able to find FFTW. So I ran `conda install fftw` (as suggested earlier in this thread). 

After installing `fftw` with conda I tried the `cmake` command again. This time I get an error because it can't find the file `FFTW3LibraryDepends.cmake`. This is [a known issue](https://github.com/FFTW/fftw3/issues/130) if you've installed it with conda, but I'm not sure what's the recommended alternative.

I hope this is helpful info for you, even if it's not directly solving your own build problems.
